// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrefinalWebApplication1.Models;

public partial class Course
{
    public int CourseID { get; set; }

    public string CourseName { get; set; }

    public string CourseDepartment { get; set; }
}