// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrefinalWebApplication1.Models;

public partial class Room
{
    public int RoomID { get; set; }

    public string RoomNumber { get; set; }

    public string Floor { get; set; }
}