// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrefinalWebApplication1.Models;

public partial class Section
{
    public int SectionID { get; set; }

    public string SectionName { get; set; }

    public string Course { get; set; }

    public string YearLevel { get; set; }
}