// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PrefinalWebApplication1.Models;

public partial class StudInfoSysContext : DbContext
{
    public StudInfoSysContext(DbContextOptions<StudInfoSysContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<Section> Sections { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.ToTable("Course");

            entity.Property(e => e.CourseID).ValueGeneratedNever();
            entity.Property(e => e.CourseDepartment)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CourseName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Room>(entity =>
        {
            entity.ToTable("Room");

            entity.Property(e => e.RoomID).ValueGeneratedNever();
            entity.Property(e => e.Floor)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RoomNumber)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Section>(entity =>
        {
            entity.ToTable("Section");

            entity.Property(e => e.SectionID).ValueGeneratedNever();
            entity.Property(e => e.Course).HasMaxLength(255);
            entity.Property(e => e.SectionName).HasMaxLength(255);
            entity.Property(e => e.YearLevel).HasMaxLength(255);
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.ToTable("Student");

            entity.Property(e => e.ContactNumber)
                .IsRequired()
                .HasMaxLength(11)
                .IsFixedLength();
            entity.Property(e => e.Course)
                .IsRequired()
                .HasMaxLength(255)
                .IsFixedLength();
            entity.Property(e => e.EmailAddress)
                .IsRequired()
                .HasMaxLength(255)
                .IsFixedLength();
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255)
                .IsFixedLength();
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255)
                .IsFixedLength();
            entity.Property(e => e.MiddleName)
                .IsRequired()
                .HasMaxLength(255)
                .IsFixedLength();
            entity.Property(e => e.Section)
                .IsRequired()
                .HasMaxLength(255)
                .IsFixedLength();
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.ToTable("Teacher");

            entity.Property(e => e.TeacherID).ValueGeneratedNever();
            entity.Property(e => e.ContactNumber)
                .IsRequired()
                .HasMaxLength(11)
                .IsFixedLength();
            entity.Property(e => e.Department)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.EmailAddress)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.MiddleName)
                .IsRequired()
                .HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}