// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrefinalWebApplication1.Models;

public partial class Teacher
{
    public int TeacherID { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string Department { get; set; }

    public string EmailAddress { get; set; }

    public string ContactNumber { get; set; }
}